### ISSUE TITLE
Could you please be adding the incus-ui-canonical on the script?

### ISSUE THREAD

**Issue by SileNt525** [oneclickvirt/incus#9]
https://github.com/zabbly/incus
Based on this project, Zabbly also provided the Incus-UI as published by Canonical. Could you please consider adding it?
So many thanks!

**Comment by spiritLHLS** [comment]
Currently there is no official front-end operation panel, you need to manually modify the configuration of the lxd panel to adapt Incus, since there is no auto-patch repository/script itself, you'd better refer to the official Youtube video given to modify the code of LXD to adapt.

https://discuss.linuxcontainers.org/t/web-ui-for-incus/18198

https://blog.simos.info/how-to-install-and-setup-the-incus-web-ui/
